version: "3.8"

services:
  reader-back:
    image: reader-back
    container_name: reader-back
    build: 
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "3999:${PORT:-3999}"
    environment:
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
    networks:
      - proxy
      - reader-back
      - postgresql
    env_file:
      - .env
    volumes:
      - ./init.sql:/init.sql
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.reader-back.rule=Host(`reader.back.maengdok.fr`)"
      - "traefik.http.routers.reader-back.entrypoints=websecure"
      - "traefik.http.routers.reader-back.tls.certresolver=myresolver"
      - "traefik.http.services.reader-back.loadbalancer.server.port=3999"

networks:
  proxy:
    external: true
  reader-back:
    external: true
  postgresql:
    external: true
