version: "3.8"

services:
  reader-back:
    image: maengdok-reader-back
    container_name: maengdok-reader-back
    build: 
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "${PORT:3999}:${PORT:-3999}"
    environment:
      - NODE_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
    networks:
      - proxy
      - reader-back
      - postgresql
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.readerback.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.readerback.entrypoints=websecure"
      - "traefik.http.routers.readerback.tls.certresolver=myresolver"

networks:
  proxy:
    external: true
  reader-back:
    external: true
  postgresql:
    external: true
